# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'

MACHINES = {
  :"nfss" => {
    :box_name => "ubuntu/jammy64",
    :cpus => 2,
    :memory => 1024,
    :ip => "192.168.50.10"
  },
  :"nfsc" => {
    :box_name => "ubuntu/jammy64",
    :cpus => 2,
    :memory => 1024,
    :ip => "192.168.50.11"
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.hostname = boxname.to_s

      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end

      # Первый интерфейс NAT (по умолчанию)
      # Второй интерфейс — private_network с заданным IP для связи между машинами
      box.vm.network "private_network", ip: boxconfig[:ip]

    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/nfs_setup.yml"
      ansible.inventory_path = "ansible/hosts"
      end
    end
  end
end

