---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install prerequisite packages
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Download Angie repository public key
  get_url:
    url: https://angie.software/keys/angie-signing.gpg
    dest: /etc/apt/trusted.gpg.d/angie-signing.gpg
    mode: '0644'
    force: true

- name: Add Angie APT repository
  ansible.builtin.shell: |
    echo "deb https://download.angie.software/angie/$(. /etc/os-release && echo "$ID/$VERSION_ID $VERSION_CODENAME") main" > /etc/apt/sources.list.d/angie.list
  args:
    executable: /bin/bash
  become: true
  changed_when: false

- name: Update apt cache after adding Angie repo
  apt:
    update_cache: yes

- name: Install Angie package
  apt:
    name: angie
    state: present

