# -*- mode: ruby -*-
# vi: set ft=ruby :

#ENV['VAGRANT_SERVER_URL'] = 'http://vagrant.elab.pro'
ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'

MACHINES = {
  :"rpm-and-repo" => {
    :box_name => "almalinux/9",
    :cpus => 2,
    :memory => 1024,
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.hostname = boxname.to_s

      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end

      # Автоматический запуск Ansible provisioning
      box.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/rpm_build.yml"
        ansible.become = true
	ansible.compatibility_mode = "2.0"
      end
    end
  end
end

