---
- name: Install NFS client package
  apt:
    name: nfs-common
    state: present
    update_cache: yes

- name: Create mount point directory
  file:
    path: /mnt
    state: directory

- name: Add NFS mount to /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: "192.168.50.10:/srv/share/ /mnt nfs vers=3,noauto,x-systemd.automount 0 0"
    state: present

- name: Reload systemd to apply automount changes
  command: systemctl daemon-reload

- name: Restart remote-fs.target to mount NFS
  systemd:
    name: remote-fs.target
    state: restarted

- name: Verify NFS mount
  shell: mount | grep /mnt
  register: mount_output
  changed_when: false

- debug:
    var: mount_output.stdout_lines

