---
- name: Install NFS server package
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Ensure /srv/share/upload directory exists
  file:
    path: /srv/share/upload
    state: directory
    owner: nobody
    group: nogroup
    mode: '0777'
    recurse: yes

- name: Configure /etc/exports for NFS share
  copy:
    dest: /etc/exports
    content: "/srv/share 192.168.50.11/32(rw,sync,root_squash)\n"
    owner: root
    group: root
    mode: '0644'

- name: Export NFS shares
  command: exportfs -r

- name: Ensure NFS server is running and enabled
  service:
    name: nfs-kernel-server
    state: started
    enabled: yes

- name: Check listening ports for NFS (optional debug)
  shell: ss -tnplu | grep -E '2049|111'
  register: nfs_ports
  changed_when: false

- debug:
    var: nfs_ports.stdout_lines

